server:
#  port: 8088
  port: ${port:8088 } # 当启动项目的时候，如果不做任何配置，那么默认端口号为8088，
  # 如果指定一个参数名为port，那么端口号为该参数

spring:
  application:
    name: springboot-imooc
  data:
    mongodb:
      database: imooc # 数据库名
      uri: mongodb://root:111@39.106.30.93:27017 # root为用户名，111为密码
  rabbitmq:
    host: 39.106.30.93  # 可以是域名或ip地址（公网ip），
    # host，如果是发布到服务器，需要修改为内网ip
    port: 5672
    username: mhq
    password: 111
    virtual-host: imooc
  redis:
    host: 39.106.30.93 # 默认localhost
    port: 6379 # 默认就是6379
    database: 0 # redis 单机单实例的情况下，默认有16个空，0代表第一个，
    password: imoocR
  thymeleaf:
    prefix: classpath:/templates/html/
    suffix: .html  # 文件后缀
  cloud:
    nacos:
      discovery:
        server-addr: 39.106.30.93:8848 # nacos服务器所在地址，ip：port
        # 如果是在生产环境，这里需要改为内网ip

# 打开监控
management:
  endpoints:
    web:
      exposure:
        include: '*'
minio:
  access-key: root
  secret-key: 123456789
  endpoint: http://39.106.30.93:9000 # Minio服务地址
  fil-host: http://39.106.30.93:9000 # 文件地址host


